### PR TITLE
Add response code when reporting errors.

### PR DESCRIPTION
**Pull request by ChristopherSchultz**
Conflicting commits causes all kinds of chaos when you don't really understand git. These 5 commits all boil down to a single line of code being changed in a single file (commit 
d0f996d ).

### CODE REVIEW

**Comment by stevoPerisic** [comment]
Are you using Git-flow for code management? Definitely shouldn't do pull req's directly to master. Let me know if I can help with Git.

**Comment by ChristopherSchultz** [comment]
I'm primarily using git on the command-line, and sometimes via Eclipse IDE. I tend to have lots of commits to my own repo that are nothing but "pull from upstream". This time, there was actually a change from upstream and a change from me and I couldn't figure out what was going on. git wouldn't give me the diff and was telling me that, basically, my only option was to "push" then merge from upstream, then push again. And that operation jacked everything up. :(

**Comment by ChristopherSchultz** [comment]
@ndonnellan Any interest in accepting this PR?

**Comment by ndonnellan** [comment]
Hey,  @ChristopherSchultz  sorry for the long delay. I no longer work on the MDP project, so these things can get lost in my inbox.

**Comment by ChristopherSchultz** [comment]
@ndonnellan Who is the new MDP GitHub maintainer, then?

**Comment by ndonnellan** [comment]
At the moment, there isn't anyone. This was my side of the desk project. I realize that's not a great response.

**Comment by stevoPerisic** [comment]
Is this project dying? Is there a need for a maintainer?

**Pull request merged**
