### PR TITLE
Fixed appending parameters

### PR DESCRIPTION
**Pull request by vnktram**
Committer: Venkataraman Rajasekaran <rvenkataraman@athenahealth.com>
 Changes to be committed:
	modified:   naive.js

### CODE REVIEW

**Review by ndonnellan — CHANGES_REQUESTED** [review]
I don't think this change meaningful improves the sample code. It just looks like you're moving simple logic of '?' + querystring(...) into a function that just does that. Was there something else you were trying to fix?

**Comment by ndonnellan** [comment]
I do appreciate the PR though. Please keep them coming!

**Comment by vnktram** [comment]
We pass in the ?querystring as one of the parameters to path_join which in turn makes the url into 
baseurl/version/practice/identifier/?querystring. (Instead of .../identifier?querystring)
This effectively makes ?querystring as a part of the path instead of being the parameter.

**Comment by ndonnellan** [comment]
I stand corrected. Although it does seem like a small function. A unit test would be a good thing to have here :-)

**Pull request merged**
